server:
  port: 8091

spring:
  cloud:
    gateway:
      routes:
      - id: user_route
        uri: http://localhost:8092 #具体地址方式
        predicates:
#        - My=/user-api/get/a #自定义匹配表达式
#        - RemoteAddr=192.168.1.1/24  #请求ip匹配，ip/子网掩码
#        - Query=name, zhangsan
#        - Query=name  #匹配查询参数包含green的请求
#        - Between=2017-01-20T17:42:47.789-07:00[Asia/Shanghai], 2017-01-21T17:42:47.789-07:00[Asia/Shanghai] #此路由匹配在2017年1月20日17点42分之后和2017年1月21日17点42分之前发出的请求。这对于维护窗口非常有用。
#        - After=2017-01-20T17:42:47.789-07:00[Asia/Shanghai] #匹配2017年1月20日以后发出的请求
#        - Before=2017-01-20T17:42:47.789-07:00[Asia/Shanghai] #匹配2017年1月20日之前发出的请求
#        - Cookie=mycookie,mycookievalue  #匹配cookie名称为mycookie且值为mycookievalue的请求,后一个参数为正则表达式
#        - Header=X-Request-Id, \d+ #请求头部匹配，两个参数，后一个参数为正则表达式
#        - Host=**.somehost.org,**.anotherhost.org #主机匹配，多个逗号隔开
#        - Method=GET,POST #匹配请求方法
#        - Path=/user-api/get/**,/user-api/delete/**
        - Path=/user-api/**
#        - Path=/get/**
        filters: #多个的话按配置上下顺序执行
#        - StripPrefix=1 #清除掉路径前缀级数: 为1：/user-api/red/a ==> /red/a  2：/user-api/red/a ==> /a
#        - SetPath=/a #重新设置路径 ，效果：/user-api/a 变成 /a
#        - RewritePath=/user-api, / #替换路径 效果：将 /user-api/get/a 变成 /get/a
#        - PrefixPath=/user-api
#        - name: CircuitBreaker  #断路器配置3，注意名称不能更改,需要添加spring-cloud-starter-netflix-hystrix依赖或spring-cloud-starter-circuitbreaker-reactor-resilience4j依赖
#          args:
#            name: myCircuitBreaker
#            fallbackUri: forward:/fallback2
#        - name: Hystrix #断路器配置2，注意名称不能更改，需要添加spring-cloud-starter-netflix-hystrix依赖，Netflix已经将Hystrix置于仅维护模式，我们建议您使用Resilience4J
#          args:
#            name: fallbackcmd
#            fallbackUri: forward:/fallback  #服务断了的话用该地址代替
#          - AddRequestHeader=X-Request-name, huangtl #添加请求头
#          - AddRequestParameter=name, huangtl #添加请求参数name=huangtl
#          - AddResponseHeader=X-Response-name, huangtl #添加响应头
#          - MapRequestHeader=host, host1 #将host请求头替换成host1请求头重新生成内容
#          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin #删除重复的响应头，空格隔开
#          - RemoveRequestHeader=x-forwarded-for #转发前删除请求头
#          - RemoveResponseHeader=Content-Length #删除响应头
#          - RemoveRequestParameter=name #删除请求参数
#          - SetRequestHeader=X-Request-Red, Blue #替换所有请求头
#          - SetResponseHeader=X-Response-Red, Blue #替换所有响应头
#          - SaveSession #传递会话状态，集成了Spring Security的话至关重要
#          - SetStatus=401 #替换http状态